spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql
common:
  slack-api-url: https://slack.com/api/chat.postMessage
  slack-token: secret
  slack-channel-id: C080X5NNG4U