spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: false
  decorator:
    datasource:
      p6spy:
        enable-logging: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql