spring:
  application:
    name: eCommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ecommerce
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
common:
  slack-api-url: https://slack.com/api/chat.postMessage
  slack-token: secret
  slack-channel-id: C080X5NNG4U